### ISSUE TITLE
Homepage down

### ISSUE THREAD

**Issue by RichardDavies** [mxunit/mxunit.github.io#1]
http://mxunit.org/ is down with a "site disabled" message.

**Comment by denuno** [comment]
Hrm, not sure what's going on there.  I'll ping somebody.  Thanks!

**Comment by virtix** [comment]
Thanks for the heads-up. Working on it.

**Comment by marcesher** [comment]
all fixed now.

Needed a) DNS change, B) change the ant-common submodule to use https instead of ssh
